/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: "https://technirvor.com",
  generateRobotsTxt: true,
  exclude: [
    "/admin/*",
    "/vendor/*",
    "/api/*",
    "/auth/password-reset",
    "/checkout/payment",
    "/profile/change-password",
  ],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/products",
          "/shops",
          "/compaigns",
          "/about",
          "/contact",
          "/profile",
          "/categories",
          "/auth",
          "/search",
          "/blog",
          "/faq",
          "/terms",
          "/privacy",
          "/product/*",
          "/shop/*",
          "/category/*",
          "/collections",
          "/offers",
          "/deals",
          "/wishlist",
          "/cart",
        ],
        disallow: [
          "/admin/*",
          "/vendor/*",
          "/api/*",
          "/auth/password-reset",
          "/checkout/payment",
          "/profile/change-password",
          "/*?*",
        ],
      },
    ],
    additionalSitemaps: [],
  },
  sitemapSize: 7000,
  changefreq: "daily",
  priority: 0.7,
};
